# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[67, 41, 36, ..., 41, 22,  6],
       [61, 25, 61, ..., 16, 69, 92],
       [13,  7,  2, ..., 74, 29, 97],
       ...,
       [48, 81, 42, ..., 33, 87, 75],
       [99, 76, 93, ..., 55, 21, 73],
       [99, 49, 13, ...,  9, 67, 37]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [2]:
A = np.transpose(A)
np.random.shuffle(A)
A = np.transpose(A)
A

array([[23, 53, 73, ..., 54, 66, 62],
       [54, 53, 82, ..., 84, 33, 97],
       [40, 74, 72, ..., 28, 67, 19],
       ...,
       [29, 91, 86, ..., 65, 21, 42],
       [49, 68, 31, ..., 87, 32, 84],
       [44, 19, 73, ..., 10, 67, 66]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [3]:
B = A[:, ::2]
C = A[:, 1::2]
B,C

(array([[23, 73, 28, ..., 19, 73, 66],
        [54, 82, 43, ..., 57, 98, 33],
        [40, 72, 37, ..., 69, 76, 67],
        ...,
        [29, 86, 93, ..., 17, 35, 21],
        [49, 31, 54, ..., 74, 24, 32],
        [44, 73, 31, ..., 24, 44, 67]]),
 array([[53, 90, 70, ..., 27, 54, 62],
        [53, 35, 98, ..., 70, 84, 97],
        [74, 12, 85, ..., 50, 28, 19],
        ...,
        [91,  2, 60, ..., 57, 65, 42],
        [68, 71, 97, ..., 22, 87, 84],
        [19, 67,  1, ..., 97, 10, 66]]))

In [4]:
B_sum = B.sum(axis=1)
C_sum = C.sum(axis=1).mean()
D = A[B_sum > C_sum]
D

array([[40, 74, 72, ..., 28, 67, 19],
       [99, 41, 47, ..., 82,  1, 66],
       [12, 42, 26, ..., 67, 23, 27],
       ...,
       [74, 77, 29, ..., 25, 30, 70],
       [49, 68, 31, ..., 87, 32, 84],
       [44, 19, 73, ..., 10, 67, 66]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [5]:
np.argmax(np.max(A, axis=1) - np.min(A, axis=1))


8

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [6]:
test_matrix = A.reshape(1, 10000)
test_matrix_next = test_matrix.argsort() + 1
arg_matrix = test_matrix_next.reshape(200, 50)
arg_matrix


array([[7127, 8745, 5746, ...,  400,  415,  423],
       [2972, 2989, 5972, ..., 5932, 5199, 1352],
       [8544, 6172, 6168, ..., 3663,  740, 3552],
       ...,
       [5011, 1981,  562, ...,  336, 3361, 9939],
       [7635, 2904, 5292, ..., 6653, 5612,  333],
       [6686, 9294, 5769, ..., 4154, 7601, 4661]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [7]:
New = (A - np.min(A)) / (np.max(A) - np.min(A))
New

array([[0.23232323, 0.53535354, 0.73737374, ..., 0.54545455, 0.66666667,
        0.62626263],
       [0.54545455, 0.53535354, 0.82828283, ..., 0.84848485, 0.33333333,
        0.97979798],
       [0.4040404 , 0.74747475, 0.72727273, ..., 0.28282828, 0.67676768,
        0.19191919],
       ...,
       [0.29292929, 0.91919192, 0.86868687, ..., 0.65656566, 0.21212121,
        0.42424242],
       [0.49494949, 0.68686869, 0.31313131, ..., 0.87878788, 0.32323232,
        0.84848485],
       [0.44444444, 0.19191919, 0.73737374, ..., 0.1010101 , 0.67676768,
        0.66666667]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [8]:
E = np.random.randint(10, 200, 50)
E

array([ 96, 116, 146, 168, 187, 163,  50, 159, 169, 161,  39,  11,  28,
       138,  17,  93,  43, 105,  90,  52, 151, 114,  44, 161, 102,  13,
        62, 187, 192,  68, 119, 115, 117,  92,  86, 170, 116,  48,  59,
       132,  17,  23,  65, 134, 103, 128,  61, 194, 101,  92])

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [9]:
A = np.concatenate((A[:, ::2], A[:, 1::2]), axis=1)
A

array([[23, 73, 28, ..., 27, 54, 62],
       [54, 82, 43, ..., 70, 84, 97],
       [40, 72, 37, ..., 50, 28, 19],
       ...,
       [29, 86, 93, ..., 57, 65, 42],
       [49, 31, 54, ..., 22, 87, 84],
       [44, 73, 31, ..., 97, 10, 66]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [10]:
np.all(A > 5, axis=1).sum()

11

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [17]:
X = np.split(A, 10)
X = np.mean(X, axis = 0)
X, X.shape

(array([[31.8, 45.8, 59. , 41.5, 51.9, 54.8, 55.9, 50.1, 53.5, 53.9, 36.4,
         42. , 69.5, 58.3, 35.9, 43.1, 50.3, 52.7, 55.4, 43.1, 42.2, 50.6,
         51.2, 56.9, 66. , 61. , 54. , 61.6, 55.8, 53.9, 36.7, 51.3, 37.8,
         55. , 47.8, 44.2, 46.4, 61.6, 44.4, 53.3, 37.6, 53.7, 33.1, 49.4,
         49.7, 54.7, 29.3, 65.5, 60.7, 35.7],
        [48.8, 46.2, 53.4, 53.6, 57.1, 60.2, 25.2, 51.1, 43. , 32.8, 63.4,
         51.2, 48.9, 58.5, 57.1, 60.1, 31.6, 52.7, 56.3, 48. , 46.9, 30.9,
         42.5, 45.4, 32. , 32.9, 44.7, 63.8, 61.9, 56.5, 49.9, 41.7, 51.3,
         32.8, 56.4, 47.4, 43.9, 60.6, 53.4, 57.9, 66. , 45.8, 50.1, 78.6,
         51.8, 37.4, 40.8, 44.7, 56.6, 51.9],
        [47.9, 46.8, 38.1, 50.7, 65. , 41.2, 55.5, 44.9, 52.9, 49.6, 62.6,
         33.3, 55.1, 28.2, 43.2, 44.8, 49.1, 61.1, 35.9, 30.1, 52.8, 52.7,
         58.4, 60. , 45.7, 62. , 51.3, 62.3, 52.6, 43.2, 35.3, 62.5, 63.9,
         43.3, 59.1, 48.9, 53.3, 45.7, 63.2, 56.2, 61.3, 63.1, 50.1, 47.1,
        

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [32]:
zew = np.unique(A, return_index=True)[1]
zew, zew.shape  

(array([ 32,  10, 118, 220,  89,  19,  31,   4,  96, 113, 188,  59,  83,
        134, 133, 160,  80, 237, 164,  15,  13, 239,  29,   0,   5,  61,
         42,  47,   2, 129,  62,  12,  95,  74, 172,  76,  18,  28,  56,
         53,  60,  11,  17,  38, 152, 174, 161, 240, 243,  58,   3,  21,
        144,  25,  43, 185,  14,  72, 181, 168, 356,  68,  49, 136, 189,
        403,  24,  34,  35,  79,  27,  45, 101,   1, 125, 103, 123, 251,
         54,  20,   8, 117,  51,   6,  33, 127, 105, 156,  92,  90,  26,
        312,  81,   9,  78,  37,  69,  36,  73, 162], dtype=int64),
 (100,))

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [13]:
G = np.where(A > 50, A, A*3)
G = np.where(A < 50, A, A*2)
G

array([[ 23, 146,  28, ...,  27, 108, 124],
       [108, 164,  43, ..., 140, 168, 194],
       [ 40, 144,  37, ..., 100,  28,  19],
       ...,
       [ 29, 172, 186, ..., 114, 130,  42],
       [ 49,  31, 108, ...,  22, 174, 168],
       [ 44, 146,  31, ..., 194,  10, 132]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [39]:
new_A = A.reshape(1, 10000)
sum(np.cumsum(new_A) / 3), sum(np.cumsum(new_A) / 5), sum(np.cumsum(new_A) / 10)

(829051842.3333356, 497431105.4000016, 248715552.7000008)

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

In [14]:
def F:
    return (5 * np.sin(2 * x) - np.power(np.cos(x), 2) - 1 + np.abs(np.power(x, 3)) - np.power(x, 2)) / (np.power(x, 2) + 1)


SyntaxError: invalid syntax (27236839.py, line 1)

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [ ]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [ ]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.