# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[26, 62, 74, ..., 89, 51, 37],
       [16, 62, 57, ...,  2, 86, 50],
       [10, 31, 83, ..., 57, 73,  4],
       ...,
       [27, 52, 51, ..., 69, 36, 59],
       [49, 88, 14, ..., 91, 92, 78],
       [65,  1, 73, ..., 12,  3, 87]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [3]:
A = np.transpose(A)
np.random.shuffle(A)
A = np.transpose(A)
A

array([[98, 44,  6, ..., 26, 38, 72],
       [74, 56, 28, ..., 16, 30, 19],
       [51, 66, 20, ..., 10, 10, 29],
       ...,
       [70, 97, 86, ..., 27,  7, 24],
       [31, 53, 11, ..., 49, 35, 43],
       [36, 79, 68, ..., 65, 90,  9]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [4]:
B = A[:, ::2]
C = A[:, 1::2]
B,C

(array([[98,  6, 62, ..., 67, 80, 38],
        [74, 28, 62, ..., 80, 77, 30],
        [51, 20, 31, ..., 10, 29, 10],
        ...,
        [70, 86, 52, ..., 93, 50,  7],
        [31, 11, 88, ..., 85, 63, 35],
        [36, 68,  1, ..., 87, 69, 90]]),
 array([[44, 69, 46, ..., 85, 26, 72],
        [56, 46, 31, ..., 25, 16, 19],
        [66, 40, 41, ..., 15, 10, 29],
        ...,
        [97, 49,  7, ...,  8, 27, 24],
        [53, 26, 54, ..., 71, 49, 43],
        [79, 60, 90, ..., 15, 65,  9]]))

In [5]:
B_sum = B.sum(axis=1)
C_sum = C.sum(axis=1).mean()
D = B_sum > C_sum
D

array([ True,  True, False, False, False, False, False,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True, False,  True,  True, False, False, False,  True, False,
        True, False, False,  True, False, False,  True,  True, False,
       False,  True,  True, False,  True,  True, False,  True, False,
        True, False, False,  True,  True,  True, False,  True, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True, False, False, False,  True, False, False, False,  True,
        True, False,  True,  True,  True, False,  True, False, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False, False,
        True,  True,

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [6]:
np.argmax(np.max(A, axis=1) - np.min(A, axis=1))

1

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [7]:
F = np.random.randint(0, 100, size=(200,50))
np.argsort(F)
np.argsort(F)


array([[31, 24,  7, ..., 17, 44, 48],
       [11, 26, 45, ..., 28, 35, 22],
       [30, 28, 48, ..., 24, 33, 25],
       ...,
       [ 1,  6,  8, ..., 20, 16, 35],
       [40,  8, 12, ..., 46, 19, 39],
       [48, 36,  1, ..., 33, 18, 14]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [14]:
New = (A-np.min(A))/(np.max(A)-np.min(A))
New

array([[0.98989899, 0.44444444, 0.06060606, ..., 0.26262626, 0.38383838,
        0.72727273],
       [0.74747475, 0.56565657, 0.28282828, ..., 0.16161616, 0.3030303 ,
        0.19191919],
       [0.51515152, 0.66666667, 0.2020202 , ..., 0.1010101 , 0.1010101 ,
        0.29292929],
       ...,
       [0.70707071, 0.97979798, 0.86868687, ..., 0.27272727, 0.07070707,
        0.24242424],
       [0.31313131, 0.53535354, 0.11111111, ..., 0.49494949, 0.35353535,
        0.43434343],
       [0.36363636, 0.7979798 , 0.68686869, ..., 0.65656566, 0.90909091,
        0.09090909]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [17]:
E = np.random.randint(10, 200, 50)
E

array([170, 153,  66, 139, 187,  71, 150,  80,  38, 193,  35, 175, 160,
       104, 115,  17, 128, 170, 169, 178, 182,  81,  87,  37, 145,  22,
        54, 123,  35,  91, 124,  26, 121,  43,  13,  33,  28, 105, 110,
        92,  36, 130, 179,  26,  64,  37, 162, 177,  42, 143])

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [18]:
A = np.concatenate((A[:, ::2], A[:, 1::2]), axis=1)
A

array([[98,  6, 62, ..., 85, 26, 72],
       [74, 28, 62, ..., 25, 16, 19],
       [51, 20, 31, ..., 15, 10, 29],
       ...,
       [70, 86, 52, ...,  8, 27, 24],
       [31, 11, 88, ..., 71, 49, 43],
       [36, 68,  1, ..., 15, 65,  9]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [20]:
np.all(A > 5, axis=1).sum()

9

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [28]:
X = np.split(A, 10, axis=0)
X = np.mean(X, axis=0)
X, X.shape

(array([[48.2, 47. , 49.3, 58.5, 65.4, 53.3, 56. , 53.5, 53.7, 50.1, 56.2,
         55. , 45.8, 51.7, 48.4, 48.8, 59.1, 60.6, 31.8, 50. , 54.3, 50.5,
         35.9, 56. , 62.3, 58.8, 53.3, 50.5, 48. , 55.6, 32.6, 47.5, 52.4,
         49.3, 44.9, 61.5, 51.6, 48.1, 55.4, 52.2, 44.8, 60.6, 43.7, 45.5,
         43.9, 63.4, 39.4, 44.7, 45.8, 53. ],
        [41.6, 55.7, 37.7, 66.4, 56.6, 51.3, 57.2, 70.9, 56.8, 54. , 37.5,
         55.5, 54.9, 42.8, 40. , 54.4, 36.9, 49.5, 62.3, 36.6, 70.2, 55.4,
         44.4, 51.7, 47.2, 47.7, 58.7, 46.3, 59.3, 50.1, 50.5, 53.7, 42.9,
         51.5, 67.9, 53.7, 60.3, 45.1, 52.2, 69.6, 49.5, 42.4, 63.1, 63.4,
         52.6, 33.6, 36.1, 24.9, 41.2, 34.4],
        [59.9, 39. , 49.2, 45. , 48.9, 50.4, 45.7, 51.4, 59.9, 49.3, 56.6,
         42.5, 47.9, 45.3, 40.5, 47. , 53.2, 58.7, 42. , 41.5, 56.7, 45.7,
         44.1, 52.3, 46.4, 55. , 52.5, 52.4, 40.3, 37.8, 51.5, 77.2, 35.1,
         51.7, 47.7, 56.1, 41.7, 66.2, 52.2, 46.8, 59.7, 55.5, 60.5, 35.7,
        

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [32]:
X = np.unique(A)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [33]:
G = np.where(A > 50, A, A*3)
G = np.where(A < 50, A, A*2)
G

array([[196,   6, 124, ..., 170,  26, 144],
       [148,  28, 124, ...,  25,  16,  19],
       [102,  20,  31, ...,  15,  10,  29],
       ...,
       [140, 172, 104, ...,   8,  27,  24],
       [ 31,  11, 176, ..., 142,  49,  43],
       [ 36, 136,   1, ...,  15, 130,   9]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

In [ ]:
def F:
    return (5 * np.sin(2 * x) - np.power(np.cos(x), 2) - 1 + np.abs(np.power(x, 3)) - np.power(x, 2)) / (np.power(x, 2) + 1)


# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [8]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 3, 3, 3]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [9]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2034

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [10]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


0.21258002608932225

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.